import json
from collections import Counter, defaultdict

SCR = r"C:/Users/cente/AppData/Local/Temp/claude/p--doc-repo/fee8e111-788c-4d0e-bd16-5510b77df32c/scratchpad"
o = json.load(open(SCR + "/alias_seed.json", encoding='utf-8'))
NAMES = {'48021': 'Bastrop', '48055': 'Caldwell', '48209': 'Hays',
         '48309': 'McLennan', '48453': 'Travis', '48491': 'Williamson'}
DIST = {'48021': 62260, '48055': 24989, '48209': 116421,
        '48309': 114255, '48453': 380918, '48491': 282570}
UNK = {'48021': (52869, 38174, 14695), '48055': (239, 0, 239), '48209': (2806, 0, 2806),
       '48309': (1739, 0, 1739), '48453': (169688, 22012, 147676), '48491': (282570, 0, 282570)}
MULTI = {'48021': 43800, '48055': 337, '48209': 0, '48309': 0, '48453': 22012, '48491': 0}

L = []
w = L.append

w("# `breadth_*` to `place_fips` alias seed — enumeration half")
w("")
w("Draft for operator confirmation. **Nothing here is written anywhere.** This is a")
w("scratchpad artifact; no product repo, no store, and no doc_repo file was touched.")
w("")
w("## Snapshot")
w("")
w("| | |")
w("|---|---|")
w("| Measured at | 2026-08-30T21:56:29Z |")
w("| Atom store | Neon project `fancy-fire-06136146` (cortex-prod), branch `br-crimson-feather-aphfmy91`, endpoint `ep-lucky-truth-apodo8hr` (direct, unpooled), **database `hauska_mcp`**, schema `public`, table `atoms` |")
w("| Store scale | `atoms` reltuples 111,241,840 over 192 GB (CLAUDE.md carries 100,025,152 / 131 GB from 2026-08-20; that figure is now stale) |")
w("| Newest `breadth_48021_*` atom | 2026-08-16T22:08:37Z |")
w("| Boundaries / roster store | same project, **database `neondb`**, tables `tx_county_boundary`, `tx_city_boundary` |")
w("| Roster file | `P:\\doc_repo\\_catalog\\texas_roster_v1.json`, `t6_roster_v1`, generated 2026-08-12T16:47:05Z; join derived 2026-08-11, 1,214 linked / 9 unlinked |")
w("| doc_repo | branch `main`, commit `97d42bb4e6ab1f0814cf4af316ae6fdac30642e0` |")
w("| Session guard | `default_transaction_read_only=on` at startup, proven by violation (below) |")
w("| `statement_timeout` | **120000 ms** for the controls, **300000 ms** for the enumeration, **540000 ms** for the two aggregate passes. No query timed out. Nothing in this document is `unmeasured`. |")
w("")
w("Credentials: `NEON_API_KEY` was found in the environment. Connection URIs were fetched")
w("from the Neon control plane for the existing `neondb_owner` role and written to two")
w("scratchpad files. No new role, branch, or endpoint was created, so there is nothing to")
w("delete at close beyond those two local files, which are removed. No secret is printed")
w("in this document or in the JSON.")
w("")
w("## Verification by violation")
w("")
w("Run before any count was believed. All four came from one `psql -f` against `hauska_mcp`.")
w("")
w("```")
w("--- session facts ---")
w("db | stmt_timeout | read_only")
w("hauska_mcp | 2min | on")
w("")
w("--- POSITIVE CONTROL: breadth_48021_ (expect >0) ---")
w("jurisdiction_tenant | n")
w("breadth_48021_bastrop | 86765")
w("breadth_48021_unknown | 67564")
w("breadth_48021_elgin-tx | 7332")
w("breadth_48021_cedar_creek | 6634")
w("breadth_48021_bastrop-city-tx | 5795")
w("(5 rows)")
w("")
w("--- NEGATIVE CONTROL A: fabricated FIPS breadth_48999_ (expect 0 rows) ---")
w("jurisdiction_tenant | n")
w("(0 rows)")
w("")
w("--- NEGATIVE CONTROL B: fabricated value (expect n=0) ---")
w("n")
w("0")
w("")
w("--- NEGATIVE CONTROL C: non-vacuity, predicate must not match everything ---")
w("matches_bastrop_prefix")
w("0")
w("```")
w("")
w("Control C is the non-vacuity fixture: `WHERE p AND NOT p` must return 0, which proves")
w("the predicate is not an always-true alternation. That is the failure mode ENFORCEMENT.md")
w("records from 2026-08-21, and it is checked here rather than assumed.")
w("")
w("Read-only was proven the same way:")
w("")
w("```")
w("$ psql ... -c \"CREATE TABLE _probe_should_fail(x int);\"")
w("ERROR:  cannot execute CREATE TABLE in a read-only transaction")
w("```")
w("")
w("**Instrument failure caught mid-run, disclosed:** the first enumeration pass was written")
w("with `psql ... | tee file | head -100`. `head` exited, `tee` took SIGPIPE, and the file was")
w("silently truncated at 141 of 226 lines. Had I read that file I would have reported ~139")
w("distinct values instead of 225. The enumeration was re-run writing to a file with no pipe.")
w("Every count below comes from the un-piped run.")
w("")
w("## The predicate")
w("")
w("The index is `atoms_jurisdiction_idx btree (jurisdiction_tenant)` with the default opclass,")
w("and `hauska_mcp` is `datcollate = C.UTF-8`. Under C collation a prefix `LIKE` compiles to a")
w("btree range condition, so the anchored form is index-driven and no unanchored `LIKE` is used:")
w("")
w("```")
w("EXPLAIN SELECT jurisdiction_tenant, count(*) FROM public.atoms")
w(" WHERE jurisdiction_tenant LIKE 'breadth\\_48021\\_%' GROUP BY 1;")
w("")
w("GroupAggregate  (cost=0.57..71.11 rows=710 width=18)")
w("  Group Key: jurisdiction_tenant")
w("  ->  Index Only Scan using atoms_jurisdiction_idx on atoms  (cost=0.57..53.38 rows=2127 width=10)")
w("        Index Cond: ((jurisdiction_tenant >= 'breadth_48021_'::text)")
w("                 AND (jurisdiction_tenant < 'breadth_48021`'::text))")
w("        Filter: (jurisdiction_tenant ~~ 'breadth\\_48021\\_%'::text)")
w("```")
w("")
w("The escaped underscores matter. `breadth_48021_%` unescaped would also admit")
w("`breadth148021x...`; escaping makes the literal underscore literal.")
w("")
w("Master enumeration, 2 min 44 s wall, no timeout:")
w("")
w("```sql")
w("SELECT jurisdiction_tenant,")
w("       count(*)                                            AS atom_rows,")
w("       count(DISTINCT (body->>'parcelNodeId'))             AS parcels,")
w("       count(*) FILTER (WHERE entity_type='road-node')      AS roads,")
w("       string_agg(DISTINCT entity_type, ',')                AS types")
w("  FROM public.atoms")
w(" WHERE jurisdiction_tenant LIKE 'breadth\\_48021\\_%'")
w("    OR jurisdiction_tenant LIKE 'breadth\\_48055\\_%'")
w("    OR jurisdiction_tenant LIKE 'breadth\\_48209\\_%'")
w("    OR jurisdiction_tenant LIKE 'breadth\\_48309\\_%'")
w("    OR jurisdiction_tenant LIKE 'breadth\\_48453\\_%'")
w("    OR jurisdiction_tenant LIKE 'breadth\\_48491\\_%'")
w(" GROUP BY 1 ORDER BY parcels DESC, atom_rows DESC;")
w("```")
w("")

w("## 1. The enumeration is finite: 225 distinct values")
w("")
w("| FIPS | County | distinct `breadth_*` values | atom rows | distinct parcels | parcels under >1 value |")
w("|---|---|---:|---:|---:|---:|")
byc = defaultdict(list)
for r in o:
    byc[r['county_fips']].append(r)
ar = {'48021': 193717, '48055': 68292, '48209': 294003,
      '48309': 208856, '48453': 726346, '48491': 689505}
for f in sorted(NAMES):
    w("| %s | %s | %d | %s | %s | %s |" % (f, NAMES[f], len(byc[f]), f"{ar[f]:,}",
                                           f"{DIST[f]:,}", f"{MULTI[f]:,}"))
w("| | **Total** | **225** | **2,180,719** | **981,413** | **66,149** |")
w("")
w("**The prior program note holds up.** It said seven spellings of Bastrop, six of Smithville,")
w("five of Cedar Creek, four of Luling. Measured independently before comparing: within 48021,")
w("Smithville is exactly 6 and Cedar Creek exactly 5; within 48055, Luling is exactly 4.")
w("Bastrop in 48021 is **7 or 8** depending on one judgement call — there are 7 spellings of")
w("the bare name (`bastrop`, `astrop`, `bastroop`, `bastropd`, `bastrrop`, `basttrop`,")
w("`batrop`) plus `bastrop-city-tx`, which is a different key *form* rather than a misspelling.")
w("Counting the bare spellings gives the note's seven. Three exact, one reproduced under a")
w("stated reading. The note was not stale.")
w("")
w("What the note did not carry is the total, and the total is the deliverable: **225 distinct")
w("values**, and Bastrop is not the worst case. Ranked by spelling count:")
w("")
w("| place | distinct `breadth_*` spellings | worst examples |")
w("|---|---:|---|")
w("| Dripping Springs (48209) | 17 | `dripping_srpings`, `drippingsprings_texas`, `dripping_spr` |")
w("| Wimberley (48209) | 14 | `womberley`, `wimbelrey`, `wmberley` |")
w("| San Marcos (48209 + 48055) | 13 | `tsan_marcos_tx`, `esan_marcos_tx`, `san_marocs` |")
w("| Bastrop (48021 + 48055) | 8 | `astrop`, `bastropd`, `basttrop` |")
w("| Smithville (48021) | 6 | `smmithville_tx`, `smihville` |")
w("| Buda (48209 + 48055) | 6 | `biuda`, `budaa` |")
w("| Cedar Creek (48021) | 5 | `ceder_creek`, `cedar_crekk` |")
w("| Elgin (48021) | 5 | `elgiin`, `elgin_t` |")
w("| Kyle (48209 + 48055) | 5 | `kyl`, `kyle_s` |")
w("| Waco (48309) | 4 | `wacxo`, `wco` |")
w("| Luling (48055) | 4 | `lulung`, `luing` |")
w("")
w("Concentration is extreme, which is what makes the confirmation pass short. The top 3 values")
w("cover 663,467 of the 1,047,727 parcel-rows (63.3 percent). **The top 25 rows cover 94.7")
w("percent.** At the other end, 112 of the 225 values carry two parcels or fewer, and 97 carry")
w("exactly one. `alias_seed.json` is sorted by `parcel_count` descending so the operator")
w("confirms in that order and can stop when the marginal row stops mattering.")
w("")

w("## 2. Confidence split")
w("")
cc = Counter(r['confidence'] for r in o)
tot = sum(r['parcel_count'] for r in o)
w("| Confidence | rows | parcel-rows | share |")
w("|---|---:|---:|---:|")
for c in ('certain', 'likely', 'needs-human'):
    s = sum(r['parcel_count'] for r in o if r['confidence'] == c)
    w("| `%s` | %d | %s | %.1f%% |" % (c, cc[c], f"{s:,}", 100.0 * s / tot))
w("| | **225** | **%s** | |" % f"{tot:,}")
w("")
w("`parcel-rows` sums `parcel_count` across values and therefore **double counts** the 66,149")
w("parcels that carry more than one `breadth_*` value. Distinct parcels are 981,413. Use the")
w("column for ordering by impact, never as a parcel population.")
w("")
w("Rule applied for `certain`: exact match to a roster place name after case and punctuation")
w("normalisation only, with the roster's own `parent_county_fips` agreeing. Anything that")
w("needed a token stripped (`-tx`, a trailing zip, the legal-status word) is `likely`, not")
w("`certain`. Nothing was promoted into `certain` on similarity.")
w("")
w("### The semantic limit on every `certain` and `likely` row")
w("")
w("An alias row maps **a string to a place**. It does **not** establish that the parcels")
w("carrying that string lie inside that place's corporate limits. CAD situs city is a")
w("**postal** city. `breadth_48209_kyle` covers 30,923 parcels; Kyle's incorporated parcel")
w("count is far smaller, and the balance is unincorporated Hays County with a Kyle mailing")
w("address. If the alias is consumed as a jurisdiction assertion, it fabricates city")
w("jurisdiction on tens of thousands of real parcels — the exact defect class this program")
w("is cleaning up. In-limits membership is a point-in-polygon question against")
w("`tx_city_boundary`, and it is a different job from this one. Every `certain` and `likely`")
w("note carries this sentence.")
w("")
w("The strongest single piece of evidence for that, in the data: 48021 carries **both**")
w("`breadth_48021_bastrop` (17,538 parcels) and `breadth_48021_bastrop-city-tx` (5,795")
w("parcels). Two keys, one place name, a 3x parcel gap. They are not the same claim.")
w("")

w("## 3. Resolution against the roster, not from my own knowledge")
w("")
w("Every proposed `place_fips` comes from `texas_roster_v1.json`. Two independent derivations")
w("are required before a misspelling is normalised:")
w("")
w("1. **Data-derived cluster head.** Within a FIPS, the highest-parcel-count spelling that")
w("   resolves in the roster becomes the anchor. Misspellings attach to it by")
w("   `difflib` ratio >= 0.82. The anchor comes from the store.")
w("2. **Roster match.** The anchor must itself resolve to a roster place whose")
w("   `parent_county_fips` or `all_county_fips` includes the FIPS. That comes from the file.")
w("")
w("One party cannot satisfy both halves: the store supplies the cluster, the roster supplies")
w("the identity and the county. Below 0.82 nothing is proposed; the row becomes `needs-human`")
w("and the note names the closest in-county roster place as a *lead*, explicitly not a mapping.")
w("")
w("A second index on the roster's `full_name` (`Bastrop city`, `Buda town`) was added after it")
w("caught a real error: `breadth_48021_bastrop-city-tx`, 5,795 parcels, was initially graded")
w("as an unincorporated place because `bastrop city` does not match the `name` field. It is")
w("consulted only on a primary-index miss and only on a single hit. One collision exists in")
w("the roster (`Clarksville City` versus `Clarksville city`); it is in Gregg County and cannot")
w("reach these six.")
w("")
w("**Straddles.** The brief's roster arithmetic reproduces exactly: 72 places hold territory")
w("in the six counties, 69 have their primary county among the six, **24 of the 72 straddle**")
w("(more than one `all_county_fips`), and exactly 3 hold territory in the six while keying to")
w("a primary county outside — Golinda, Staples, Thorndale. That is the 72-versus-69 gap.")
w("Statewide the roster carries 203 straddling places; the 24 is the six-county subset, and")
w("the two numbers are not in conflict.")
w("")
w("Five rows in this seed are straddles. They are graded `likely`, not flagged as errors:")
w("")
w("| value | parcels | place | primary county |")
w("|---|---:|---|---|")
for r in o:
    if r['kind'] == 'straddle':
        w("| `%s` | %s | %s | %s |" % (r['breadth_value'], f"{r['parcel_count']:,}",
                                       r['proposed_place_name'], r['note'].split('primary county ')[1].split(')')[0] + ')'))
w("")
w("Golinda, Staples and Thorndale — the three that hold territory in the six while keying to a")
w("primary county outside — **do not appear in the store at all**. No `breadth_*` value names")
w("any of them, in any spelling. They are a roster-side concern and generate no alias row, so")
w("the seed does not need a special case for them.")
w("")

w("## 4. Out-of-county values, classified")
w("")
w("24 rows name a place whose roster county does not include the FIPS they are filed under,")
w("covering 20 distinct place names. County adjacency was computed with PostGIS on")
w("`neondb.tx_county_boundary` rather than asserted:")
w("")
w("```sql")
w("WITH g AS (SELECT county_fips, ST_MakeValid(ST_GeomFromGeoJSON(geometry::text)) AS geom")
w("             FROM public.tx_county_boundary)")
w("SELECT a.county_fips, b.county_fips FROM g a JOIN g b")
w("  ON a.county_fips <> b.county_fips AND ST_Intersects(a.geom, b.geom)")
w(" WHERE a.county_fips IN ('48021','48055','48209','48309','48453','48491');")
w("```")
w("")
w("```")
w("48021: 48055 48149 48287 48453 48491")
w("48055: 48021 48149 48177 48187 48209 48453")
w("48209: 48031 48055 48091 48187 48453")
w("48309: 48027 48035 48099 48145 48217 48293")
w("48453: 48021 48031 48053 48055 48209 48491")
w("48491: 48021 48027 48053 48287 48331 48453")
w("```")
w("")
w("| value | parcels | names | its county | class |")
w("|---|---:|---|---|---|")
for r in sorted([x for x in o if x['kind'] in ('c-undecidable', 'b-cad-error')],
                key=lambda x: -x['parcel_count']):
    n = r['note']
    if 'ROSTER GAP' in n:
        cls = "**(c) undecidable** — roster gap, no county on the roster row"
        cty = "unknown"
    elif r['kind'] == 'b-cad-error':
        cls = "**(b) CAD data error**"
        cty = n.split('CLASS b-cad-error: ')[1].split(' sits in ')[1].split(',')[0].split(' (')[0]
    else:
        cls = "(c) undecidable — adjacent county, postal spillover"
        cty = n.split('sits in ')[1].split(',')[0].split(' which')[0].strip()
    w("| `%s` | %s | %s | %s | %s |" % (r['breadth_value'], f"{r['parcel_count']:,}",
                                        r['proposed_place_name'], cty, cls))
w("")
w("**(a) Straddle:** none of these. Straddles were resolved upstream against `all_county_fips`")
w("and are the five `likely` rows in section 3. A straddle is not an out-of-county row.")
w("")
w("**(b) CAD data error — one row.** `breadth_48021_waelder`, 62 parcels. Waelder is in")
w("Gonzales (48177). Bastrop's adjacent counties are 48055, 48149, 48287, 48453, 48491.")
w("48177 is not among them, so a postal spillover across an intervening county is implausible")
w("and this reads as bad situs text. It is the only row where adjacency rules out the benign")
w("explanation. Note the same string in Caldwell (`breadth_48055_waelder`, 56 parcels) is")
w("**legitimate** — 48177 does border 48055.")
w("")
w("**(c) Undecidable from here — 23 rows.** In every one the named place sits in a county")
w("that physically touches the filing county. CAD situs city is a postal city and postal")
w("cities routinely cross county lines, so an out-of-county name on a parcel near the county")
w("line is expected behaviour, not evidence of an error. A point-in-polygon test would settle")
w("each; the roster alone cannot. `breadth_48055_kyle` (1,017 parcels) is the one worth")
w("looking at first on volume alone.")
w("")
w("**The roster gap.** `breadth_48055_harwood` (456 parcels) is undecidable for a different")
w("reason: the roster row for Harwood is one of the 9 with no `parent_county_fips` and an")
w("empty `all_county_fips`, so adjacency cannot be tested at all. That is a roster defect")
w("surfacing as an alias question, and it should be fixed in the roster rather than decided here.")
w("")
w("**Reconciling the prior 'eight cities not in Bastrop County'.** In 48021 I measure **seven**")
w("roster-resolvable out-of-county city names — Austin, Flatonia, Giddings, La Grange,")
w("Lexington, Manor, Waelder — plus **two** out-of-county postal places that are not in the")
w("roster, Del Valle and Dale. Seven or nine depending on whether the unincorporated pair")
w("counts. The prior figure of eight sits between the two readings; I cannot reproduce it")
w("exactly and am not going to round to it.")
w("")

w("## 5. What the alias table cannot fix")
w("")
w("Three populations here, and they need three different dispositions. None of them is an")
w("alias row.")
w("")
w("### 5a. Not a jurisdiction at all — 21 rows")
w("")
w("| value | parcels | why |")
w("|---|---:|---|")
for r in sorted([x for x in o if x['kind'] == 'not-a-jurisdiction'], key=lambda x: -x['parcel_count']):
    why = r['note'].split('NOT A JURISDICTION (')[1].split(')')[0]
    w("| `%s` | %s | %s |" % (r['breadth_value'], f"{r['parcel_count']:,}", why))
w("")
w("Six of the 21 are the literal `unknown` token and they carry essentially all the weight:")
w("509,911 parcel-rows against 17 for the other fifteen combined. The other fifteen are road")
w("fragments (`co_rd`, `cr102`, `empire_st`, `&_pareya_dr`, `berwick_ct,_mackintosh_ct`), CAD")
w("remark text (`houses_only`, `owner_responsibilty`, `behind_joe_romer's`, `training_center`),")
w("an internal code (`m66626`, `0896.11s44a`), and a county abbreviation (`guad_co`). Correct")
w("disposition for all 21 is `unknown` under the four-state contract. An alias row for any of")
w("them would be a fabricated jurisdiction.")
w("")
w("### How much of the corpus is `unknown`, and how much is recoverable")
w("")
w("This is the number that matters most, so it was measured against distinct parcels rather")
w("than inferred. A parcel can carry `unknown` on one atom and a real city on another, in")
w("which case the second atom recovers it without any alias work:")
w("")
w("| FIPS | County | parcels touching `unknown` | also under a named value | `unknown` only | `unknown`-only share of county |")
w("|---|---|---:|---:|---:|---:|")
for f in sorted(NAMES):
    t, r_, u = UNK[f]
    w("| %s | %s | %s | %s | **%s** | %.1f%% |" % (f, NAMES[f], f"{t:,}", f"{r_:,}", f"{u:,}",
                                                   100.0 * u / DIST[f]))
w("| | **Total** | **509,911** | **60,186** | **449,725** | **45.8%** |")
w("")
w("**449,725 of 981,413 parcels — 45.8 percent — have no jurisdiction string anywhere in the")
w("store.** No alias table reaches them. They need a spatial assignment or a re-ingest, and")
w("they are the actual long pole, not the spelling variants.")
w("")
w("The distribution is the finding. Williamson is 282,570 parcels under a single value,")
w("`breadth_48491_unknown`, and nothing else — one distinct value for the whole county, zero")
w("recoverable. Travis is 147,676 unknown-only against three total values. Between them the")
w("two largest counties in the program are 96 percent of the unknown-only population, and the")
w("alias table does nothing for either. Bastrop is the opposite case: 38,174 of its 52,869")
w("unknown-touching parcels are recoverable from a second atom, because 43,800 of its 62,260")
w("parcels carry more than one `breadth_*` value.")
w("")
w("### 5b. Real places with no `place_fips` to map to — 40 rows, 17 distinct places")
w("")
w("These are not misspellings and not errors. They are unincorporated communities, CDPs, and")
w("postal places that appear in CAD situs and **have no row in the target vocabulary**:")
w("")
w("- `texas_roster_v1.json` carries 1,223 **incorporated** cities.")
w("- `neondb.tx_city_boundary` carries 1,222 rows, all incorporated.")
w("- Probed directly for Cedar Creek, Driftwood, Del Valle, Manchaca, Paige, McDade, Red Rock,")
w("  Rosanky, Dale, Maxwell, Elm Mott, China Spring, Axtell, Henly, Fischer, Prairie Lea,")
w("  Fentress, Eddy, Bruceville: **0 of 19 present in either source.**")
w("")
w("| value | parcels | reads as |")
w("|---|---:|---|")
for r in sorted([x for x in o if x['kind'] == 'unincorporated-place-no-place-fips'],
                key=lambda x: -x['parcel_count'])[:12]:
    w("| `%s` | %s | %s |" % (r['breadth_value'], f"{r['parcel_count']:,}", r['proposed_place_name']))
w("")
w("36,287 parcel-rows sit under these 40 values. **The declared target form `place_fips`")
w("cannot express them at all**, so this is not a hand-seeding task that more effort finishes;")
w("it is an operator ruling. Three options, and the choice belongs to the operator:")
w("")
w("1. Extend the roster with Census CDP place FIPS, giving these a real `place_fips`.")
w("2. Add an explicit `unincorporated` disposition distinct from `unknown`, so a Cedar Creek")
w("   parcel is honestly typed rather than collapsed into the 45.8 percent.")
w("3. Map them to the county and drop the postal name, losing real signal.")
w("")
w("Option 2 preserves the distinction between *we do not know* and *we know it is")
w("unincorporated*, which the four-state contract already asks for and which option 3 destroys.")
w("Bruceville and Eddy are a special case inside this bucket: both lead to the incorporated")
w("**Bruceville-Eddy** (place_fips 10828), so 2,286 parcels across those two values may be a")
w("clean `certain` mapping once a human confirms the two halves of the hyphenated name.")
w("")
w("### 5c. Wrong scope, not wrong spelling — 4 rows")
w("")
w("| value | parcels | road-node atoms | reading |")
w("|---|---:|---:|---|")
for r in sorted([x for x in o if x['kind'] in ('county-level-key', 'mixed-scope-key')],
                key=lambda x: -x['road_node_rows']):
    rd = "county-scoped only" if r['parcel_count'] == 0 else "**mixed**: county roads and parcels under one string"
    w("| `%s` | %s | %s | %s |" % (r['breadth_value'], f"{r['parcel_count']:,}",
                                   f"{r['road_node_rows']:,}", rd))
w("")
w("All four free texts are **county** names, and all four collide with an incorporated city")
w("name elsewhere in Texas. A naive roster lookup resolves `breadth_48309_mclennan` to nothing")
w("but resolves `breadth_48055_caldwell` to **Caldwell city in Burleson County** and")
w("`breadth_48209_hays` to **Hays city** — both wrong, and both would look like clean")
w("`certain` matches to a seeder working from the string alone. This is the trap that would")
w("have fired first.")
w("")
w("`breadth_48021_bastrop` is the worst of the four: 36,802 county road-node atoms **and**")
w("17,538 parcels under one string, while a separate `breadth_48021_bastrop-city-tx` carries")
w("the 5,795 city-stamped parcels. It cannot be aliased to a single `place_fips` until the")
w("two scopes are split. I graded it `needs-human` for that reason, overriding what was")
w("otherwise an exact roster match on `Bastrop`.")
w("")
w("Entity-type composition across all 225 values, which is where the road/parcel split comes from:")
w("")
w("| entity_type | atom rows | distinct `breadth_*` values |")
w("|---|---:|---:|")
w("| `zoning-fact` | 981,415 | 222 |")
w("| `buildable-envelope` | 707,394 | 159 |")
w("| `setback-rule` | 344,698 | 13 |")
w("| `road-node` | 120,366 | 4 |")
w("| `property-boundary-edge` | 26,846 | 1 |")
w("")
w("Note there are **no `parcel-node` atoms** under any `breadth_*` tenant. `parcel_count` in")
w("the JSON is `count(DISTINCT body->>'parcelNodeId')`, which is the parcel population these")
w("facet atoms attach to, not a count of parcel nodes.")
w("")

w("## 6. What a human still has to decide")
w("")
w("Ordered by what unblocks the most.")
w("")
w("1. **The 45.8 percent.** `unknown`-only is 449,725 parcels and the alias table does not")
w("   touch it. Williamson and Travis are 96 percent of it. Decide whether that is a spatial")
w("   assignment job or a re-ingest before treating the alias table as the long pole; on these")
w("   numbers it is not the long pole.")
w("2. **The `place_fips` vocabulary gap.** 40 values / 17 real postal places have no")
w("   `place_fips` in any source held. Rule on CDP extension versus an `unincorporated`")
w("   disposition. Until that is ruled, those 40 rows cannot be seeded at all.")
w("3. **The four mixed-scope keys.** Split county roads from parcels, or the first four")
w("   confident-looking mappings in the table are wrong.")
w("4. **Confirm the top 25 rows.** 94.7 percent of parcel weight. Should be a short pass.")
w("5. **`breadth_48021_waelder`** (62 parcels) — the one probable CAD situs error.")
w("6. **`breadth_48055_harwood`** (456 parcels) — fix the roster row, then re-run the class.")
w("7. **Ten unresolved rows** (79 parcel-rows total) where the nearest spelling sits just")
w("   under the 0.82 threshold: `moddy`->Moody at 0.80, `mt_calm`->Mount Calm at 0.80,")
w("   `kylr`->Kyle at 0.75, `dael`->Dale at 0.75. Each note names the lead. I did not promote")
w("   them; a human eyeball is cheaper than a fabricated mapping.")
w("")

w("## 7. What I could not resolve, stated plainly")
w("")
w("- **In-limits membership for any row.** Not attempted. Requires point-in-polygon against")
w("  `tx_city_boundary`. Every `certain` and `likely` row is a string-to-place claim only.")
w("- **The county of any unincorporated place.** Del Valle, Dale, Cedar Creek and the other 14 of the 17")
w("  are absent from both roster and boundary table, so I cannot say from a source which county")
w("  they sit in. I did not fill this from my own knowledge.")
w("- **Harwood's county.** Roster gap, 9 unlinked rows, adjacency untestable.")
w("- **Whether the 23 `(c)` rows are spillover or error.** Adjacency rules out the error")
w("  reading for none of them and rules it in for none. It is genuinely undecidable without geometry.")
w("- **`breadth_48309_cavitt` and `breadth_48309_shadow_ridge`** (1 parcel each). They read as")
w("  a street and a subdivision, but neither matched a road-fragment pattern and neither is")
w("  near any place name. Left `unresolved` rather than guessed into the non-jurisdiction bucket.")
w("- **Why Travis has 3 values and Williamson 1** while Hays has 87. That is a difference in")
w("  how each county's CAD situs was ingested, not something this enumeration explains. It is")
w("  worth asking, because Williamson having exactly one value and it being `unknown` looks")
w("  more like a dropped field at ingest than a property of Williamson CAD.")
w("")

w("## Alternative mechanism, considered and rejected")
w("")
w("The observation is 225 distinct values with heavy misspelling. The mechanism I state is")
w("unnormalised free-text CAD situs carried through to the tenant key.")
w("")
w("The second mechanism that would produce the same observation: multiple ingest runs with")
w("different normalisation rules, so `bastrop` and `bastrop-city-tx` are two *eras* rather than")
w("two *sources*. I rejected it as the sole explanation but not entirely: 43,800 of 62,260")
w("Bastrop parcels carry more than one `breadth_*` value, which is exactly what era-layering")
w("looks like, and it matches the known `ENVELOPE-BEHIND-STAMP` defect in")
w("`90_operations/onboarding_defect_class_backlog.md` where a re-stamp left older-tenant")
w("envelopes behind. But era-layering cannot explain `wacxo`, `brucville`, or")
w("`behind_joe_romer's`, which are keystroke-level source text. **Both mechanisms are")
w("operating.** That matters for the fix: an alias table addresses the free-text half, and")
w("nothing in it addresses the era half. Deduplicating a parcel that carries two tenants is a")
w("separate card.")
w("")
w("## Files")
w("")
w("- `alias_seed.json` — 225 objects, sorted by `parcel_count` descending. Required keys")
w("  `breadth_value`, `county_fips`, `parcel_count`, `proposed_place_fips`,")
w("  `proposed_place_name`, `confidence`, `note`, plus `county_name`, `atom_rows`,")
w("  `road_node_rows`, `entity_types`, `kind`.")
w("- `alias_seed.md` — this file.")
w("- `master_raw.tsv` — raw enumeration output, un-piped.")
w("- `adjacency.txt` — raw PostGIS adjacency output.")
w("- `build_alias.py`, `gen_md.py` — the instruments.")
w("")
w("`confidence` describes the **string-to-place** proposal only. `kind` carries why.")

open(SCR + "/alias_seed.md", "w", encoding='utf-8').write("\n".join(L) + "\n")
print("wrote alias_seed.md", len(L), "lines")
